src/app/components/connection-window/connection-window.component.html

Is there any reason to don't use this?
I can't run the tests, so I don't know if some tests fails with this.

Added type="password" in the main-window

---

src/app/components/editors/creature/creature-onkill-reputation/creature-onkill-reputation.integration.spec.ts

Added Creature Onkill Reputation integration test

test: add CreatureOnkillReputation integration test

---

src/app/components/editors/gameobject/gameobject-template-addon/gameobject-template-addon.component.html
src/app/components/editors/gameobject/gameobject-template-addon/gameobject-template-addon.component.ts
src/app/components/editors/gameobject/gameobject-template-addon/gameobject-template-addon.integration.spec.ts
src/app/components/editors/gameobject/gameobject-template-addon/gameobject-template-addon.module.ts
src/app/components/editors/gameobject/gameobject.module.ts
src/app/components/main-window/sidebar/sidebar.component.html
src/app/config/app-routing.module.ts
src/app/services/editors/gameobject/gameobject-template-addon.service.spec.ts
src/app/services/editors/gameobject/gameobject-template-addon.service.ts
src/app/types/gameobject-questitem.type.ts
src/app/types/gameobject-template-addon.type.ts

Added Gameobject Template Addon.
Fixed gamebject_questitem and gameobject_template_addon types (table name).

Added Gameobject Template Addon, added minor fixes

---

src/app/components/editors/quest/quest-request-items/quest-request-items.integration.spec.ts

test: fix flaky test

---

src/app/components/editors/creature/creature-spawn-addon/creature-spawn-addon.component.html
src/app/components/editors/creature/creature-spawn-addon/creature-spawn-addon.integration.spec.ts
src/app/components/editors/creature/creature-template-addon/creature-template-addon.component.html
src/app/components/editors/creature/creature-template-addon/creature-template-addon.integration.spec.ts
src/app/types/creature-spawn-addon.type.ts
src/app/types/creature-template-addon.type.ts

- Closes #123 
Thanks @Stoabrogga for the core implementation (https://github.com/azerothcore/azerothcore-wotlk/pull/2304)

feat(creature/addon): add isLarge field

---

src/app/components/editors/gameobject/gameobject-template-addon/gameobject-template-addon.integration.spec.ts
src/app/constants/flags/gameobject-flags.ts

Fixed go_flags types

---

package-lock.json
package.json

Update serialize-javascript version to prevent vulnerabilities

Update serialize-javascript version to prevent vulnerabilities

---

src/app/components/editors/smart-scripts/sai-editor/constants/sai-event.ts

chore(SAI): check constants event

---

src/app/services/editors/sai/sai-editor.service.spec.ts
src/app/services/editors/sai/sai-editor.service.ts
src/app/services/handlers/sai-handler.service.spec.ts
src/app/services/handlers/sai-handler.service.ts

chore(SAI): generate template queries

---

src/app/components/editors/smart-scripts/sai-search-existing/sai-search-existing.integration.spec.ts
src/app/services/query.service.spec.ts
src/app/services/query.service.ts
src/app/services/search/sai-search.service.ts
src/app/services/search/search.service.spec.ts
src/app/services/search/search.service.ts

fix(SAI/search): solve issue with duplicate search results

---

tsconfig.json

https://angular.io/guide/angular-compiler-options

chore(tsconfig): improve angular compiler options

---

src/app/shared/abstract/service/editors/multi-row-editor.service.ts
src/app/shared/abstract/service/handlers/handler.service.ts
src/app/shared/modules/sai-editor/sai-editor.component.html
src/app/shared/modules/sai-editor/sai-editor.component.integration.spec.ts
src/app/shared/modules/sai-editor/sai-editor.component.ts
src/app/shared/modules/sai-editor/sai-editor.service.ts

- Closes https://github.com/azerothcore/Keira3/issues/353

fix(SAI): disable event type for timed action lists

---

src/app/shared/modules/sai-editor/sai-editor.service.ts

fix(SAI/Comments): close #378

---

README.md

doc(README.md): add Windows development instructions

---

src/app/main/app.component.ts
src/app/shared/services/mysql-query.service.ts
src/app/shared/services/query.service.ts
src/app/shared/services/sqlite-query.service.spec.ts
src/app/shared/services/sqlite-query.service.ts
src/app/shared/services/sqlite.service.ts

- move future shared code into a common `QueryService` abstract class
- fix sqlite service to make it work with array of rows too

refactor: sqlite service

---

src/app/shared/modules/sai-editor/constants/sai-comments.ts

fix(SAI): missing comment for event_type 2 closes #441

---

e2e/common-setup.ts
main.ts

feat(main): exit confirm dialog

---

src/app/features/creature/creature-equip-template/creature-equip-template.component.html
src/app/features/creature/creature-equip-template/creature-equip-template.integration.spec.ts
src/app/features/creature/creature-equip-template/creature-equip-template.module.ts
src/app/features/creature/creature-questitem/creature-questitem.component.html
src/app/features/creature/npc-vendor/npc-vendor.component.html
src/app/features/creature/npc-vendor/npc-vendor.integration.spec.ts
src/app/features/gameobject/gameobject-loot-template/gameobject-loot-template.component.html
src/app/features/gameobject/gameobject-questitem/gameobject-questitem.component.html
src/app/features/item/item-loot-template/item-loot-template.component.html
src/app/features/quest/quest-template/quest-template.component.html
src/app/features/quest/quest-template/quest-template.integration.spec.ts
src/app/features/quest/quest-template/quest-template.module.ts
src/app/shared/abstract/components/editors/loot-template/loot-template.component.html
src/app/shared/modules/icon/icon.component.html
src/app/shared/modules/icon/icon.component.scss
src/app/shared/modules/icon/icon.component.ts
src/app/shared/modules/icon/icon.service.spec.ts
src/assets/scss/editor.scss
src/assets/scss/ngx-datatable.scss

- Closes https://github.com/azerothcore/Keira3/issues/459

feat(icons): add item icons to single editors too

---

src/app/main/main-window/sidebar/sidebar.component.ts
src/app/shared/modules/sai-editor/sai-editor.component.html

- Closes https://github.com/azerothcore/Keira3/issues/466

fix(datatable): fix size bug

---

src/app/shared/modules/sai-editor/sai-editor.component.html
src/app/shared/modules/sai-editor/timed-actionlist/timed-actionlist.component.html
src/app/shared/modules/sai-editor/timed-actionlist/timed-actionlist.component.spec.ts
src/app/shared/modules/sai-editor/timed-actionlist/timed-actionlist.component.ts

- Closes https://github.com/azerothcore/Keira3/issues/379

feat(SAI): display Timed Actionlists of creatures

---

src/app/features/creature/creature-questitem/creature-questitem.component.html
src/app/features/creature/creature-spawn-addon/creature-spawn-addon.component.html
src/app/features/creature/creature-spawn/creature-spawn.component.html
src/app/features/creature/npc-trainer/npc-trainer.component.html
src/app/features/creature/npc-vendor/npc-vendor.component.html
src/app/features/gameobject/gameobject-loot-template/gameobject-loot-template.component.html
src/app/features/gameobject/gameobject-questitem/gameobject-questitem.component.html
src/app/features/gameobject/gameobject-spawn/gameobject-spawn.component.html
src/app/features/gossip/gossip-menu-option/gossip-menu-option.component.html
src/app/features/gossip/gossip-menu/gossip-menu.component.html
src/app/features/item/item-enchantment/item-enchantment-template.component.html
src/app/features/item/item-loot-template/item-loot-template.component.html
src/app/features/item/select-item/select-item.component.html
src/app/features/quest/creature-questender/creature-questender.component.html
src/app/features/quest/creature-queststarter/creature-queststarter.component.html
src/app/features/quest/gameobject-questender/gameobject-questender.component.html
src/app/features/quest/gameobject-queststarter/gameobject-queststarter.component.html
src/app/shared/abstract/components/editors/loot-template/loot-template.component.html
src/app/shared/modules/sai-editor/sai-editor.component.html
src/app/shared/modules/selectors/item-selector/item-selector-modal.component.html

- Further improves: https://github.com/azerothcore/Keira3/issues/466

fix(datatable): more improvement to the size of columns

---

src/app/features/dashboard/dashboard.component.html
src/app/features/dashboard/dashboard.component.spec.ts
src/app/features/dashboard/dashboard.component.ts

- Closes https://github.com/azerothcore/Keira3/issues/469

feat(dashboard): check for correct DB version

---

src/app/shared/modules/icon/icon.service.spec.ts
src/app/shared/modules/icon/icon.service.ts

Removed `.tga` from the icon name, close #487.

fix(iconName): remove .tga from icon name, close #487

---

src/app/shared/modules/sai-editor/constants/sai-comments.ts

- Closes https://github.com/azerothcore/Keira3/issues/359

feat(SAI/CommentGenerator): add AC-only actions

---

src/app/features/creature/creature-questitem/creature-questitem.component.html
src/app/features/creature/npc-trainer/npc-trainer.component.html
src/app/features/creature/npc-trainer/npc-trainer.component.ts
src/app/features/creature/npc-trainer/npc-trainer.integration.spec.ts
src/app/features/creature/npc-vendor/npc-vendor.component.html
src/app/features/gameobject/gameobject-questitem/gameobject-questitem.component.html
src/app/features/quest/creature-questender/creature-questender.component.html
src/app/features/quest/creature-questender/creature-questender.integration.spec.ts
src/app/features/quest/creature-queststarter/creature-queststarter.component.html
src/app/features/quest/creature-queststarter/creature-queststarter.integration.spec.ts
src/app/features/quest/gameobject-questender/gameobject-questender.component.html
src/app/features/quest/gameobject-questender/gameobject-questender.integration.spec.ts
src/app/features/quest/gameobject-queststarter/gameobject-queststarter.component.html
src/app/features/quest/gameobject-queststarter/gameobject-queststarter.integration.spec.ts
src/app/shared/services/sqlite-query.service.ts

- Closes https://github.com/azerothcore/Keira3/issues/513
- Closes https://github.com/azerothcore/Keira3/issues/523

feat: add names to lists

---

src/app/features/creature/creature-spawn/creature-spawn.component.html
src/app/features/creature/creature-spawn/creature-spawn.integration.spec.ts
src/app/features/creature/creature-spawn/creature-spawn.module.ts
src/app/features/gameobject/gameobject-spawn/gameobject-spawn.component.html
src/app/features/gameobject/gameobject-spawn/gameobject-spawn.module.ts
src/app/features/item/item-template/item-template.component.html
src/app/features/item/item-template/item-template.integration.spec.ts
src/app/features/item/item-template/item-template.module.ts
src/app/shared/testing/editor-page-object.ts
src/app/shared/testing/page-object.ts

- Closes https://github.com/azerothcore/Keira3/issues/490

feat: add Map selector

---

src/app/features/creature/npc-trainer/npc-trainer.component.html
src/app/features/creature/npc-trainer/npc-trainer.integration.spec.ts
src/app/features/creature/npc-trainer/npc-trainer.module.ts
src/app/features/creature/npc-vendor/npc-vendor.component.html
src/app/features/creature/npc-vendor/npc-vendor.integration.spec.ts
src/app/features/creature/npc-vendor/npc-vendor.module.ts
src/app/features/quest/quest-template-addon/quest-template-addon.component.html
src/app/features/quest/quest-template-addon/quest-template-addon.module.ts
src/app/shared/modules/selectors/item-enchantment-selector/item-enchantment-selector-modal.component.html
src/app/shared/modules/selectors/item-extended-cost-selector/item-extended-cost-selector-modal.component.html
src/app/shared/modules/selectors/item-limit-category-selector/item-limit-category-selector-modal.component.html

- Closes https://github.com/azerothcore/Keira3/issues/524
- Closes https://github.com/azerothcore/Keira3/issues/510

feat: add more selectors

---

src/app/features/creature/creature-template/creature-template.component.html
src/app/features/creature/creature-template/creature-template.module.ts
src/app/features/quest/creature-queststarter/creature-queststarter.integration.spec.ts
src/app/shared/modules/selectors/creature-selector/creature-selector-modal.component.html

https://github.com/azerothcore/Keira3/issues/538

feat: add more creature selectors + tests

---

src/app/shared/abstract/service/editors/multi-row-complex-key-editor.service.ts
src/app/shared/abstract/service/editors/multi-row-editor.service.ts
src/app/shared/modules/sai-editor/sai-editor.component.html

- Closes https://github.com/azerothcore/Keira3/issues/553

feat(SAI): make ID editable + fix bug in display error

---

src/app/features/smart-scripts/sai-search-entity/sai-search-entity.component.html
src/app/features/smart-scripts/sai-search-entity/sai-search-entity.component.scss
src/app/features/smart-scripts/sai-search-entity/sai-search-entity.component.spec.ts
src/app/features/smart-scripts/sai-search-entity/sai-search-entity.component.ts
src/assets/scss/_utils.scss

- Closes https://github.com/azerothcore/Keira3/issues/568

feat(SAI): improve Search by Entity

---

src/app/features/item/item-template/item-preview.service.ts

fix(item-preview): add null check for inventory type

---

src/app/features/item/item-template/item-preview.service.spec.ts
src/app/features/item/item-template/item-preview.service.ts
src/app/features/item/item-template/item-template.component.html
src/app/features/item/item-template/item-template.component.scss
src/app/features/item/item-template/item-template.component.ts
src/app/features/item/item-template/item-template.module.ts
src/app/shared/modules/icon/icon.component.ts
src/assets/scss/_item-preview.scss

fix(item-preview): improve icon, fix spell description

---

src/app/features/item/item-template/item-template.component.html

chore(item-template): improve item template editor layout

---

src/app/main/connection-window/connection-window.component.html
src/app/main/connection-window/connection-window.component.scss
src/app/main/connection-window/connection-window.component.spec.ts
src/app/main/connection-window/connection-window.component.ts
src/app/main/connection-window/connection-window.module.ts

- Closes https://github.com/azerothcore/Keira3/issues/556

feat(login): save multiple login sessions

---

src/app/features/creature/creature-spawn/creature-spawn.component.html
src/app/features/creature/creature-spawn/creature-spawn.integration.spec.ts
src/app/shared/types/creature-spawn.type.ts

This will be necessary when https://github.com/azerothcore/azerothcore-wotlk/pull/2858 is pushed. 
This is the only file I found with spawndist in it... if there is another just poke me :P

chore(creature-spawn.type): rename 'spawndist' to 'wander_distance'

---

src/app/shared/modules/sai-editor/constants/sai-actions.ts

https://github.com/azerothcore/azerothcore-wotlk/pull/2878

chore(sai-actions.ts): Implement description new feature of SMART_ACTION_SET_IN_COMBAT_WITH_ZONE

---

src/app/features/quest/quest-preview/quest-preview.component.html
src/app/features/quest/quest-preview/quest-preview.component.spec.ts
src/app/features/quest/quest-preview/quest-preview.service.spec.ts
src/app/features/quest/quest-preview/quest-preview.service.ts

Quests for testing:
```
10130 - npc or go
11731 - only objective text
1369 - rep + item
6823 - only rep
8762
```

chore(quest-preview-required): add required NpC, Gameobject, Item and Faction

---

src/app/features/quest/quest-offer-reward/quest-offer-reward.integration.spec.ts
src/app/features/quest/quest-preview/quest-preview.component.html
src/app/features/quest/quest-preview/quest-preview.component.scss
src/app/features/quest/quest-preview/quest-preview.component.spec.ts
src/app/features/quest/quest-preview/quest-preview.component.ts
src/app/features/quest/quest-preview/quest-preview.service.spec.ts
src/app/features/quest/quest-preview/quest-preview.service.ts
src/app/features/quest/quest-request-items/quest-request-items.integration.spec.ts
src/app/features/quest/quest.module.ts

- Closes https://github.com/azerothcore/Keira3/issues/664

chore(quest-preview): add texts

---

src/app/shared/modules/sai-editor/constants/sai-targets.ts
src/app/shared/modules/sai-editor/sai-editor.component.html
src/app/shared/modules/sai-editor/sai-editor.component.integration.spec.ts
src/app/shared/modules/sai-editor/sai-editor.component.ts

- Closes https://github.com/azerothcore/Keira3/issues/611

feat(SAI): add dynamic names/tooltips to Target* fields

---

src/app/features/creature/creature-questitem/creature-questitem.component.html
src/app/features/creature/creature-spawn-addon/creature-spawn-addon.component.html
src/app/features/creature/creature-spawn/creature-spawn.component.html
src/app/features/creature/npc-trainer/npc-trainer.component.html
src/app/features/creature/npc-vendor/npc-vendor.component.html
src/app/features/gameobject/gameobject-loot-template/gameobject-loot-template.component.html
src/app/features/gameobject/gameobject-questitem/gameobject-questitem.component.html
src/app/features/gameobject/gameobject-spawn/gameobject-spawn.component.html
src/app/features/gossip/gossip-menu-option/gossip-menu-option.component.html
src/app/features/gossip/gossip-menu/gossip-menu.component.html
src/app/features/item/item-enchantment/item-enchantment-template.component.html
src/app/features/item/item-loot-template/item-loot-template.component.html
src/app/features/quest/creature-questender/creature-questender.component.html
src/app/features/quest/creature-queststarter/creature-queststarter.component.html
src/app/features/quest/gameobject-questender/gameobject-questender.component.html
src/app/features/quest/gameobject-queststarter/gameobject-queststarter.component.html
src/app/shared/abstract/components/editors/loot-template/loot-template.component.html
src/app/shared/modules/sai-editor/sai-editor.component.html

- Closes https://github.com/azerothcore/Keira3/issues/733

feat(multi-row-editors): use delete key to delete rows

---

src/app/shared/modules/loot-editor/reference-viewer.component.html

- Closes https://github.com/azerothcore/Keira3/issues/763

fix(reference-viewer): disable selection status

---

main.ts

Builds
Tested on Windows and all works as it should :) 
closes https://github.com/azerothcore/Keira3/issues/658

feat(main.ts): Add Keira3 navigation bar

---

package-lock.json
src/app/shared/modules/sai-editor/sai-handler.service.spec.ts
src/app/shared/modules/sai-editor/sai-handler.service.ts

This PR will:
- fix https://github.com/azerothcore/Keira3/issues/803
- add a new test case that will automatically catch such bug
- while I was there, I did some refactoring to the existing tests too
Thanks @Jinnaix for reporting this bug.

fix(SAI/Actionlist): correct get entity name query

---

main.ts
package-lock.json

See: https://github.com/electron/electron/issues/24221

fix(main.ts): 'Image could not be created from' error

---

package-lock.json

Ajv is Another JSON Schema Validator and old versions  of this package are vulnerable to Prototype Pollution. A carefully crafted JSON schema could be provided that allows execution of other code by prototype pollution. (While untrusted schemas are recommended against, the worst case of an untrusted schema should be a denial of service, not execution of code.).
**Prototype Pollution** refers to the ability to inject properties into existing JavaScript language construct prototypes, such as objects. JavaScript allows all Object attributes to be altered, including their magical attributes such as `_proto_`,` constructor` and `prototype`. An attacker manipulates these attributes to overwrite, or pollute, a JavaScript application object prototype of the base object by injecting other values. …

Upgrade of older versions of Ajv, Minimist and node-addon-api

---

package-lock.json

Reverts azerothcore/Keira3#929

Revert "Upgrade of older versions of Ajv, Minimist and node-addon-api"

---

src/app/shared/modules/selectors/base-selector/base-selector-btn.component.ts
src/app/shared/modules/selectors/base-selector/base-selector-modal.component.ts
src/app/shared/modules/selectors/base-selector/base-selector.model.ts
src/app/shared/modules/selectors/flags-selector/flags-selector-btn.component.ts
src/app/shared/modules/selectors/flags-selector/flags-selector-modal.component.spec.ts
src/app/shared/modules/selectors/flags-selector/flags-selector-modal.component.ts
src/app/shared/modules/selectors/flags-selector/flags-selector.model.ts
src/app/shared/modules/selectors/single-value-selector/single-value-selector-btn.component.ts
src/app/shared/modules/selectors/single-value-selector/single-value-selector-modal.component.spec.ts
src/app/shared/modules/selectors/single-value-selector/single-value-selector-modal.component.ts
src/app/shared/modules/selectors/single-value-selector/single-value-selector.model.ts

Needed for: https://github.com/azerothcore/Keira3/issues/966

refactor(modals): add type in modal configs

---

src/app/shared/modules/selectors/flags-selector/flags.service.spec.ts
src/app/shared/modules/selectors/flags-selector/flags.service.ts

- Closes https://github.com/azerothcore/Keira3/issues/966

fix(flags-selector): do not use -1 to select all flags

---

src/app/shared/constants/options/creature-class.ts

- Closes https://github.com/azerothcore/Keira3/issues/985
thanks @JamesGent for reporting this

fix(creature-template): trainer class selector values

---

src/app/features/quest/quest-offer-reward/quest-offer-reward.component.html
src/app/features/quest/quest-template/quest-template.component.html

close https://github.com/azerothcore/Keira3/issues/992
results:

chore(quest-offer-reward): [3.0.2] convert RewardText input to textarea

---

src/app/shared/constants/flags/inhabit-type.ts

closes https://github.com/azerothcore/Keira3/issues/1027

fix(inhabit-types): implement 'ROOT'

---

src/app/features/creature/creature-template/creature-template.component.html
src/app/features/creature/creature-template/creature-template.component.ts
src/app/features/creature/creature-template/creature-template.integration.spec.ts
src/app/shared/constants/flags/spell-school-immune-mask.ts
src/app/shared/types/creature-template.type.ts

closes https://github.com/azerothcore/Keira3/issues/1074

feat(creature_template): spell_school_immune_mask

---

package-lock.json
package.json

Reverts azerothcore/Keira3#1097

Revert "chore(deps): update dependency electron-builder to v22.10.5"

---

README.md

Client does not support authentication protocol requested by server; consider upgrading MySQL client
More information about it here:
https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

Authentication protocol

---

src/app/features/creature/creature-template/creature-template.component.html
src/app/features/creature/creature-template/creature-template.integration.spec.ts
src/app/shared/types/creature-template.type.ts

Align `creature_template` editor with https://github.com/azerothcore/azerothcore-wotlk/pull/4749
@Hacki95 can you please suggest some Tooltips for the 2 new fields?

fix(creature-template): align to latest AC damage changes

---

src/app/features/item/item-enchantment/item-enchantment-template.integration.spec.ts
src/app/shared/abstract/service/editors/editor.service.ts
src/app/shared/abstract/service/editors/single-row-complex-key-editor.service.spec.ts
src/app/shared/abstract/service/editors/single-row-complex-key-editor.service.ts
src/app/shared/modules/query-output/query-output.component.html
src/app/shared/modules/query-output/query-output.component.spec.ts
src/app/shared/modules/query-output/query-output.component.ts

Suggested by @Stifler82 - New "Reload" button in all editors:

feat(all-editors): Reload button

---

src/app/features/spell/spell-dbc/spell-dbc.component.html
src/app/features/spell/spell-dbc/spell-dbc.module.ts
src/app/features/spell/spell-dbc/texts/spell-dbc-locale/spell-dbc-locale.component.html
src/app/features/spell/spell-dbc/texts/spell-dbc-locale/spell-dbc-locale.component.spec.ts
src/app/features/spell/spell-dbc/texts/spell-dbc-locale/spell-dbc-locale.component.ts
src/app/features/spell/spell-dbc/texts/spell-dbc-texts.component.html
src/app/features/spell/spell-dbc/texts/spell-dbc-texts.component.ts
src/app/features/spell/spell-dbc/texts/spell-dbc-texts.model.ts

chore(spell-dbc): texts

---

src/app/features/spell/spell-dbc/spell-dbc.component.integration.spec.ts

- Updates https://github.com/azerothcore/Keira3/issues/1190

test(spell-dbc): integration tests part 2

---

src/app/features/dashboard/dashboard.component.html
src/app/features/dashboard/dashboard.component.ts

new "Keira Details" row including the system version (version of OS, chrome, electron, etc...)

feat(Dashboard): show Keira system information (navigator.appVersion)

---

src/app/shared/modules/sai-editor/constants/sai-event.ts

Negative value is not used in event_param
**Issues Addressed:**
Closes #1286

Correction of incorrect description

---

package-lock.json
package.json

11 is not supported by ngx-highlightjs yet

fix(deps): revert to highlightjs 10

---

src/app/features/quest/quest-template/quest-template.component.html
src/app/features/quest/quest-template/quest-template.integration.spec.ts
src/app/shared/types/quest-template.type.ts

- Closes https://github.com/azerothcore/Keira3/issues/1516

feat(quest-template): RewardMoneyDifficulty

---

src/app/main/connection-window/connection-window.component.ts

ref https://github.com/dirkluijk/ngx-typesafe-forms/issues/26

refactor(forms): remove type hack

---

src/app/features/creature/creature-spawn/creature-spawn.integration.spec.ts
src/app/shared/types/creature-spawn.type.ts

fix https://github.com/azerothcore/Keira3/issues/1634

fix: make creature-spawn compatible with latest AC

---

src/app/features/creature/creature-spawn-addon/creature-spawn-addon.component.html
src/app/features/creature/creature-spawn-addon/creature-spawn-addon.integration.spec.ts
src/app/features/creature/creature-spawn-addon/creature-spawn-addon.service.spec.ts
src/app/features/creature/creature-spawn-addon/creature-spawn-addon.service.ts
src/app/features/creature/creature-template-addon/creature-template-addon.component.html
src/app/features/creature/creature-template-addon/creature-template-addon.integration.spec.ts
src/app/shared/types/creature-spawn-addon.type.ts
src/app/shared/types/creature-template-addon.type.ts

- Ref https://github.com/azerothcore/azerothcore-wotlk/pull/9180

fix(Creature): Template Addon, Spawn, Spawn Addon compatibility with latest AC

---

src/app/features/item/item-template/item-preview.service.ts
src/app/shared/modules/sai-editor/sai-handler.service.spec.ts
src/app/shared/modules/sai-editor/sai-handler.service.ts
src/app/shared/services/mysql-query.service.spec.ts
src/app/shared/services/mysql-query.service.ts

- Closes https://github.com/azerothcore/Keira3/issues/1665

fix: Item Preview and other corrections

---

src/karma.conf.js

test: (partially) fix coverage

---

src/app/shared/constants/flags/smart-event-flags.ts

- Fixes https://github.com/azerothcore/Keira3/issues/2050

fix(SAI/event_flags): add SMART_EVENT_FLAG_WHILE_CHARMED

---

main.ts

closes https://github.com/azerothcore/Keira3/issues/2068
Thanks @Samsequel

fix: open wiki url in the desktop browser, closes #2068

---

src/app/scss/_ngx-bootstrap.scss

- Closes https://github.com/azerothcore/Keira3/issues/2067
- Caused by https://github.com/valor-software/ngx-bootstrap/issues/6490

fix(ngx-bootstrap): workaround for Tooltip issue

---

src/app/shared/modules/sai-editor/sai-editor.service.ts

fix: SAI generate comment, closes #1820

---

src/app/features/gameobject/gameobject-template-addon/gameobject-template-addon.component.html
src/app/features/gameobject/gameobject-template-addon/gameobject-template-addon.integration.spec.ts
src/app/shared/types/gameobject-template-addon.type.ts

closes https://github.com/azerothcore/Keira3/issues/2087

fix: add missing fields in gameobject-template-addon

---

src/app/shared/modules/switch-language/switch-language.component.html
src/app/shared/modules/switch-language/switch-language.component.spec.ts
src/app/shared/modules/switch-language/switch-language.component.ts
src/app/shared/modules/switch-language/switch-language.module.ts
src/app/shared/modules/switch-language/switch-language.service.spec.ts
src/app/shared/modules/switch-language/switch-language.service.ts

closes https://github.com/azerothcore/Keira3/issues/2073

fix: switch language persistent

---

src/app/shared/modules/sai-editor/constants/sai-actions.ts

closes https://github.com/azerothcore/Keira3/issues/2130
@Gultask should be correct, right?

chore: add SAI tooltip for CALL_TIMED_ACTIONLIST

---

src/app/shared/constants/flags/creature-type-flags.ts
src/app/shared/modules/sai-editor/constants/sai-targets.ts

closes https://github.com/azerothcore/Keira3/issues/1696

chore: improve tooltips, closes #1696

---

src/assets/i18n/de.json
src/assets/i18n/el.json
src/assets/i18n/en.json
src/assets/i18n/es.json
src/assets/i18n/fr.json
src/assets/i18n/it.json
src/assets/i18n/ko.json
src/assets/i18n/nl.json
src/assets/i18n/pl.json
src/assets/i18n/pt.json
src/assets/i18n/ro.json
src/assets/i18n/ru.json
src/assets/i18n/sk.json
src/assets/i18n/sv.json
src/assets/i18n/zh.json

closes https://github.com/azerothcore/Keira3/issues/2180

chore: improve visibility distance tooltip

---

src/app/features/smart-scripts/sai-search-existing/sai-search-existing.component.html
src/app/features/smart-scripts/sai-search-existing/sai-search-existing.component.ts
src/app/features/smart-scripts/sai-search-existing/sai-search-existing.integration.spec.ts

closes https://github.com/azerothcore/Keira3/issues/2255

fix: default selection SAI

---

src/app/main/app.component.ts
src/app/main/connection-window/connection-window.component.html
src/app/main/connection-window/connection-window.component.scss
src/app/main/connection-window/connection-window.component.spec.ts
src/app/main/connection-window/connection-window.component.ts
src/app/main/connection-window/connection-window.service.spec.ts
src/app/main/connection-window/connection-window.service.ts
src/app/main/main-window/sidebar/logout-btn/logout-btn.component.spec.ts
src/app/main/main-window/sidebar/logout-btn/logout-btn.component.ts
src/app/shared/services/local-storage.service.ts
src/assets/i18n/de.json
src/assets/i18n/el.json
src/assets/i18n/en.json
src/assets/i18n/es.json
src/assets/i18n/fr.json
src/assets/i18n/it.json
src/assets/i18n/ko.json
src/assets/i18n/nl.json
src/assets/i18n/pl.json
src/assets/i18n/pt.json
src/assets/i18n/ro.json
src/assets/i18n/ru.json
src/assets/i18n/sk.json
src/assets/i18n/sv.json
src/assets/i18n/zh.json

closes https://github.com/azerothcore/Keira3/issues/1215

feat: implement remember-me

---

src/app/features/creature/sai-creature/sai-creature.component.integration.spec.ts
src/app/features/gameobject/sai-gameobject/sai-gameobject.component.integration.spec.ts
src/app/shared/modules/sai-editor/constants/sai-event.ts
src/app/shared/modules/sai-editor/sai-editor.component.html
src/app/shared/modules/sai-editor/sai-editor.component.integration.spec.ts
src/app/shared/modules/sai-editor/sai-editor.component.ts
src/app/shared/modules/sai-editor/sai-editor.service.ts
src/app/shared/types/smart-scripts.type.ts

closes https://github.com/azerothcore/Keira3/issues/2394

feat: add event_param6 to SAI editor

---

src/app/shared/modules/sai-editor/constants/sai-targets.ts

Correct SAI SMART_TARGET_HOSTILE_RANDOM_NOT_TOP tooltip

---

src/app/features/dashboard/dashboard.component.html
src/app/features/dashboard/dashboard.component.spec.ts
src/app/features/dashboard/dashboard.component.ts

- Fix URL of AC commit when ending with a `+`
- Remove function call from template (performance)
- Refactored tests
- Enabled previous disabled test

fix(dashboard): AC commit link + minor perf improvement

---

package-lock.json
package.json

- Closes https://github.com/azerothcore/Keira3/issues/2575

chore(deps): remove deprecated codelyzer

---

src/app/shared/constants/flags/spell-dbc-flags-flags.ts

Changed from 21 to 31 due to a typo.

NoCategoryCooldownMods fixed wrong bit number

---

src/app/features/creature/creature-template-movement/creature-template-movement.component.ts

fix: creature template movement documentation link, closes #2646

---

src/app/features/item/item-template/item-template.component.ts

fix: item preview output

---

.github/workflows/main.yml
.github/workflows/windows.yml
nx.json
package.json

Reason to exclude "Keira3": https://stackoverflow.com/questions/78093551/nx-remove-root-project-from-lint-targets

chore: use nx affected for linting

---

.eslintrc.json
apps/keira/project.json
libs/features/conditions/project.json
libs/features/creature/project.json
libs/features/dashboard/project.json
libs/features/gameobject/project.json
libs/features/gossip/project.json
libs/features/item/project.json
libs/features/other-loots/project.json
libs/features/quest/project.json
libs/features/smart-scripts/project.json
libs/features/spell/project.json
libs/features/sql-editor/project.json
libs/main/connection-window/project.json
libs/main/main-window/project.json
libs/shared/acore-world-model/project.json
libs/shared/config/project.json
libs/shared/constants/project.json
libs/shared/core/project.json
libs/shared/login-config/project.json
libs/shared/model-3d-viewer/project.json
libs/shared/test-utils/project.json

- See: https://nx.dev/features/enforce-module-boundaries#tags

chore(nx/boundaries): prevent chaos

---

libs/features/gameobject/src/gameobject-questitem/gameobject-questitem.component.html

fix(gameobject-questitem): itemId in keira3-icon

---

libs/features/texts/src/npc-text/npc-text-fields-group.component.html
libs/features/texts/src/npc-text/npc-text-fields-group.component.spec.ts
libs/features/texts/src/npc-text/npc-text-fields-group.component.ts
libs/features/texts/src/npc-text/npc-text.component.html
libs/features/texts/src/npc-text/npc-text.component.ts
libs/shared/test-utils/src/lib/editor-page-object.ts
libs/shared/test-utils/src/lib/page-object.ts

- Adding helper component for the npc_text editor

chore: npc_text editor fields

---

libs/features/conditions/src/edit-conditions/conditions.component.html

- Closes https://github.com/azerothcore/Keira3/issues/2988

feat(conditions): show value in Source and Type select options

---

apps/keira/src/assets/i18n/de.json
apps/keira/src/assets/i18n/el.json
apps/keira/src/assets/i18n/es.json
apps/keira/src/assets/i18n/fr.json
apps/keira/src/assets/i18n/it.json
apps/keira/src/assets/i18n/ko.json
apps/keira/src/assets/i18n/nl.json
apps/keira/src/assets/i18n/pl.json
apps/keira/src/assets/i18n/pt.json
apps/keira/src/assets/i18n/ro.json
apps/keira/src/assets/i18n/ru.json
apps/keira/src/assets/i18n/sk.json
apps/keira/src/assets/i18n/sv.json

source https://www.azerothcore.org/wiki/creature#equipmentid
the values in the db are -1, 0, 1 and 2
I do not know what is 2

chore(text): creature equipment_id update tooltip

---

libs/shared/acore-world-model/src/flags/special-flags.ts

- azerothcore/azerothcore-wotlk#19116
- azerothcore/wiki#969

chore(special-flags.ts): add SpecialFlags 64 and 128

---

libs/shared/sai-editor/src/constants/sai-actions.ts

https://github.com/azerothcore/azerothcore-wotlk/pull/19190

fix(Scripts/SmartAI): Rewrite ACTION_MOVE_TO_POS 

---

libs/features/creature/src/creature-template/creature-template.component.html
libs/features/creature/src/creature-template/creature-template.component.ts
libs/features/creature/src/creature-template/creature-template.integration.spec.ts
libs/shared/acore-world-model/src/entities/creature-template.type.ts

- Fixes https://github.com/azerothcore/Keira3/issues/3027

fix(creature-template): editor + disable creature-preview

---

libs/features/creature/src/creature-text/creature-text.service.ts
libs/shared/acore-world-model/src/entities/creature-text.type.ts
libs/shared/base-abstract-classes/src/core.mock.ts
libs/shared/base-abstract-classes/src/service/editors/multi-row-editor.service.spec.ts
libs/shared/base-abstract-classes/src/service/editors/multi-row-editor.service.ts
libs/shared/switch-language/src/switch-language.service.ts

closes https://github.com/azerothcore/Keira3/issues/3008
this PR could help in the future for https://github.com/azerothcore/Keira3/issues/2242

feat(multi-row-editor): add a second special ID per row when necessary

---

apps/keira/src/assets/i18n/de.json
apps/keira/src/assets/i18n/el.json
apps/keira/src/assets/i18n/en.json
apps/keira/src/assets/i18n/es.json
apps/keira/src/assets/i18n/fr.json
apps/keira/src/assets/i18n/it.json
apps/keira/src/assets/i18n/ko.json
apps/keira/src/assets/i18n/nl.json
apps/keira/src/assets/i18n/pl.json
apps/keira/src/assets/i18n/pt.json
apps/keira/src/assets/i18n/ro.json
apps/keira/src/assets/i18n/ru.json
apps/keira/src/assets/i18n/sk.json
apps/keira/src/assets/i18n/sv.json
apps/keira/src/assets/i18n/zh.json

column name `RewardSpellCast`  was changed to  `RewardSpell` in table `quest_template`

rename RewardSpellCast to RewardSpell

---

libs/shared/acore-world-model/src/options/quest-type.ts

related of https://github.com/azerothcore/wiki/pull/1003

chore: remove quest type 3

---

libs/features/sql-editor/src/sql-editor.component.html

closes https://github.com/azerothcore/Keira3/issues/3039

chore(sql-editor.component.html): add horizontal scrollbar

---

libs/shared/base-abstract-classes/src/components/editors/editor.component.ts
libs/shared/base-abstract-classes/src/service/handlers/handler.service.spec.ts
libs/shared/base-abstract-classes/src/service/handlers/handler.service.ts

closes https://github.com/azerothcore/Keira3/issues/3059

feat(handler-service): implement force reload

---

libs/features/creature/src/creature-template-model/creature-template-model.component.html
libs/features/creature/src/creature-template-model/creature-template-model.component.scss
libs/features/creature/src/creature-template-model/creature-template-model.component.ts
libs/features/creature/src/creature-template-model/creature-template-model.integration.spec.ts
libs/features/creature/src/creature-template-model/creature-template-model.service.spec.ts
libs/features/creature/src/creature-template/creature-template.component.html
libs/features/creature/src/creature-template/creature-template.component.ts
libs/features/gameobject/src/gameobject-template/gameobject-template.component.html
libs/features/gameobject/src/gameobject-template/gameobject-template.component.ts
libs/features/item/src/item-template/item-template.component.html
libs/shared/model-3d-viewer/src/model-3d-viewer.component.html
libs/shared/model-3d-viewer/src/model-3d-viewer.component.ts

closes https://github.com/azerothcore/Keira3/issues/3015

feat(creature-template-model): enable black the creature 3d model preview

---

libs/shared/acore-world-model/src/flags/special-flags.ts

closes https://github.com/azerothcore/Keira3/issues/3045

chore(quest-special-flags): add missing special flag value

---

libs/features/item/src/item-template/item-template.component.html
libs/features/item/src/item-template/item-template.component.ts
libs/features/item/src/item-template/item-template.integration.spec.ts

closes https://github.com/azerothcore/Keira3/issues/2667

feat(item-template): calculate automatically stats count on stat_value change

---

libs/features/creature/src/creature-text/creature-text.component.html
libs/features/creature/src/creature-text/creature-text.integration.spec.ts
libs/shared/acore-world-model/src/entities/creature-text.type.ts

closes https://github.com/azerothcore/Keira3/issues/3053

fix(creature-text): set proper primary key 2 (still missing pk3 management)

---

libs/features/quest/src/quest-preview/quest-preview.component.html
libs/features/quest/src/quest-preview/quest-preview.component.ts
libs/features/quest/src/quest-preview/quest-preview.model.ts
libs/features/quest/src/quest-preview/quest-preview.service.spec.ts
libs/features/quest/src/quest-preview/quest-preview.service.ts
libs/shared/constants/src/constants/preview.ts

closes https://github.com/azerothcore/Keira3/issues/2681
Tested with the following Quest IDs:
- **1**  ([wowhead](https://www.wowhead.com/wotlk/quest=1), [wowgaming](https://wowgaming.altervista.org/aowow/?quest=1) )
- **7065**  ([wowhead](https://www.wowhead.com/wotlk/quest=7065), [wowgaming](https://wowgaming.altervista.org/aowow/?quest=7065) )
- **500**  ([wowhead](https://www.wowhead.com/wotlk/quest=500), [wowgaming](https://wowgaming.altervista.org/aowow/?quest=500) )

feat(quest-preview): support RewardOverrideFaction

---

apps/keira/src/assets/i18n/de.json
apps/keira/src/assets/i18n/el.json
apps/keira/src/assets/i18n/en.json
apps/keira/src/assets/i18n/es.json
apps/keira/src/assets/i18n/fr.json
apps/keira/src/assets/i18n/it.json
apps/keira/src/assets/i18n/ko.json
apps/keira/src/assets/i18n/nl.json
apps/keira/src/assets/i18n/pl.json
apps/keira/src/assets/i18n/pt.json
apps/keira/src/assets/i18n/ro.json
apps/keira/src/assets/i18n/ru.json
apps/keira/src/assets/i18n/sk.json
apps/keira/src/assets/i18n/sv.json
apps/keira/src/assets/i18n/zh.json
libs/shared/base-editor-components/src/query-output/query-output.component.html
libs/shared/base-editor-components/src/query-output/query-output.component.spec.ts
libs/shared/test-utils/src/lib/query-output-page-object.ts

closes https://github.com/azerothcore/Keira3/issues/3037

feat(query-output): add execute and copy button

---

libs/features/spell/src/select-spell/select-spell.component.html
libs/shared/base-editor-components/src/create/create.component.html
libs/shared/base-editor-components/src/create/create.component.spec.ts
libs/shared/base-editor-components/src/create/create.component.ts

closes https://github.com/azerothcore/Keira3/issues/984

feat(create.component): set max ID value

---

index.html

feat: add internals link in navbar

---

libs/shared/acore-world-model/src/flags/socket-color.ts

- Closes https://github.com/azerothcore/Keira3/issues/3142 https://github.com/azerothcore/Keira3/pull/3149

fix(item_template): fix socket colors bit values

---

apps/keira/src/assets/i18n/de.json
apps/keira/src/assets/i18n/el.json
apps/keira/src/assets/i18n/en.json
apps/keira/src/assets/i18n/es.json
apps/keira/src/assets/i18n/fr.json
apps/keira/src/assets/i18n/it.json
apps/keira/src/assets/i18n/ko.json
apps/keira/src/assets/i18n/nl.json
apps/keira/src/assets/i18n/pl.json
apps/keira/src/assets/i18n/pt.json
apps/keira/src/assets/i18n/ro.json
apps/keira/src/assets/i18n/ru.json
apps/keira/src/assets/i18n/sk.json
apps/keira/src/assets/i18n/sv.json
apps/keira/src/assets/i18n/zh.json
libs/features/creature/src/creature-spawn/creature-spawn.component.html
libs/features/creature/src/creature-spawn/creature-spawn.integration.spec.ts
libs/shared/acore-world-model/src/entities/creature-spawn.type.ts

Tested on own device. 
I also added entries (placeholders) for the new addition (comment) in the creature section.

feat(creature-spawn): add new column comment

---

apps/keira/src/assets/i18n/de.json
apps/keira/src/assets/i18n/el.json
apps/keira/src/assets/i18n/en.json
apps/keira/src/assets/i18n/es.json
apps/keira/src/assets/i18n/fr.json
apps/keira/src/assets/i18n/it.json
apps/keira/src/assets/i18n/ko.json
apps/keira/src/assets/i18n/nl.json
apps/keira/src/assets/i18n/pl.json
apps/keira/src/assets/i18n/pt.json
apps/keira/src/assets/i18n/ro.json
apps/keira/src/assets/i18n/ru.json
apps/keira/src/assets/i18n/sk.json
apps/keira/src/assets/i18n/sv.json
apps/keira/src/assets/i18n/zh.json

fix(i18n): key for conditions

---

libs/features/creature/src/creature-template/creature-template.integration.spec.ts
libs/shared/acore-world-model/src/entities/creature-template.type.ts

chore(creature_template): update initial unit class from being 0 to 1 (warrior class)

---

apps/keira/src/app/scss/_item-select.scss
libs/features/item/src/item-enchantment/item-enchantment-template.component.html
libs/features/item/src/item-handler.service.ts
libs/features/item/src/item-template/item-template.component.html
libs/features/item/src/select-item/select-item.component.html
libs/shared/base-abstract-classes/src/components/editors/loot-template/loot-template-id.component.html
libs/shared/base-abstract-classes/src/components/editors/loot-template/loot-template.component.html
libs/shared/base-abstract-classes/src/service/handlers/handler.service.spec.ts
libs/shared/base-abstract-classes/src/service/handlers/handler.service.ts
libs/shared/base-abstract-classes/src/service/select/select.service.spec.ts
libs/shared/base-abstract-classes/src/service/select/select.service.ts
libs/shared/base-editor-components/src/top-bar/top-bar.component.html
libs/shared/base-editor-components/src/top-bar/top-bar.component.spec.ts
libs/shared/base-editor-components/src/top-bar/top-bar.component.ts

Closes #3247
I adjusted the handler to hold a new property, for the item quality. Maybe there is a better word for it?
Everything works, but two tests fail and I cannot figure out why.
Thats my output. 
Any ideas @Francesco-Borzi or @Helias 
Maybe you have another idea on how to solve that?

Improve item quality visibility

---

apps/keira/src/assets/i18n/de.json
apps/keira/src/assets/i18n/el.json
apps/keira/src/assets/i18n/en.json
apps/keira/src/assets/i18n/es.json
apps/keira/src/assets/i18n/fr.json
apps/keira/src/assets/i18n/it.json
apps/keira/src/assets/i18n/ko.json
apps/keira/src/assets/i18n/nl.json
apps/keira/src/assets/i18n/pl.json
apps/keira/src/assets/i18n/pt.json
apps/keira/src/assets/i18n/ro.json
apps/keira/src/assets/i18n/ru.json
apps/keira/src/assets/i18n/sk.json
apps/keira/src/assets/i18n/sv.json
apps/keira/src/assets/i18n/zh.json
libs/features/creature/src/creature-template/creature-template.component.html

An addition to the changes to the wiki (to make it clear for users using Keira and the wiki for documentation). (with this PR: https://github.com/azerothcore/wiki/pull/1068)
Previous PR had un-wanted commits for some reason.

[Corrected] Adds clarification (hint) to Faction (in creature_template) 

---

apps/keira/src/app/app.component.html
apps/keira/src/app/app.component.scss
apps/keira/src/app/app.component.spec.ts

closes https://github.com/azerothcore/Keira3/issues/3387

feat(app): close button for newer version

---

libs/shared/sai-editor/src/sai-handler.service.spec.ts
libs/shared/sai-editor/src/sai-handler.service.ts

- Closes https://github.com/azerothcore/Keira3/issues/3500

fix(SAI): infinite loop bug

---

libs/features/creature/src/creature-template/creature-template.component.html
libs/features/creature/src/creature-template/creature-template.component.ts

closes https://github.com/azerothcore/Keira3/issues/3529

chore(creature-template): remove Model reference from creature-template
