azerothcore/Keira3

- src/app/features/item/item-template/item-template.component.html
- src/app/features/item/item-template/item-template.module.ts
- src/app/features/quest/quest-template-addon/quest-template-addon.component.html
- src/app/features/quest/quest-template-addon/quest-template-addon.integration.spec.ts
- src/app/features/quest/quest-template-addon/quest-template-addon.module.ts
- src/app/shared/modules/search/quest-search.service.spec.ts
- src/app/shared/modules/search/quest-search.service.ts
- src/app/shared/modules/selectors/quest-selector/quest-selector-btn.component.spec.ts
- src/app/shared/modules/selectors/quest-selector/quest-selector-btn.component.ts
- src/app/shared/modules/selectors/quest-selector/quest-selector-modal.component.html
- src/app/shared/modules/selectors/quest-selector/quest-selector-modal.component.spec.ts
- src/app/shared/modules/selectors/quest-selector/quest-selector-modal.component.ts
- src/app/shared/modules/selectors/quest-selector/quest-selector.module.ts
- Closes https://github.com/azerothcore/Keira3/issues/537
> feat: implement quest-selector

- src/app/features/conditions/edit-conditions/conditions.component.html
- src/app/features/conditions/edit-conditions/conditions.component.ts
- src/app/features/conditions/edit-conditions/conditions.integration.spec.ts
Add tests for:
- https://github.com/azerothcore/Keira3/pull/708
- https://github.com/azerothcore/Keira3/pull/706
> test: add coverage for recently added features

- .github/workflows/main.yml
- README.md
- package.json
Advantages:
- Build and e2e steps separated in the CI, so we see which one fails
- So you can build the app once, and run the e2e multiple times without rebuilding
> chore: split build and e2e steps

- README.md
- The SQL statement is modified.
- Field information is added.
Currently, when using MySQL 8.x, it is necessary to change the encryption as specified in the readme, however, the connection type must be clarified, which is what I am adding. Take this opportunity to upload a detail of what the values mean within the SQL statement.
> Modify information in README.md about MySQL

- src/app/features/creature/creature-template/creature-template.component.html
- src/app/features/creature/creature-template/creature-template.component.ts
- src/app/features/creature/creature-template/creature-template.integration.spec.ts
- src/app/shared/types/creature-template.type.ts
With https://github.com/azerothcore/azerothcore-wotlk/pull/9272 the column `InhabitType` from the `creature_template` table was removed. This PR adapts Keira3 to these changes.
An editor component for the new table `creature_template_movement` should be created.
> fix(creature): adapt to removed InhabitType column

- src/app/config/app-routing.module.ts
- src/app/features/creature/creature-handler.service.ts
- src/app/features/creature/creature-template-movement/creature-template-movement.component.html
- src/app/features/creature/creature-template-movement/creature-template-movement.component.ts
- src/app/features/creature/creature-template-movement/creature-template-movement.integration.spec.ts
- src/app/features/creature/creature-template-movement/creature-template-movement.module.ts
- src/app/features/creature/creature-template-movement/creature-template-movement.service.spec.ts
- src/app/features/creature/creature-template-movement/creature-template-movement.service.ts
- src/app/features/creature/creature.module.ts
- src/app/main/main-window/sidebar/sidebar.component.html
- src/app/shared/types/creature-template-movement.type.ts
This PR adds functionality for the [creature_template_movement](https://www.azerothcore.org/wiki/creature_template_movement) table. The table is now editable in the editor.
The tests I added seem to pass, but I'm not really familiar with the testing library which gets used.
Select a random creature and look at the **Template Movement** tab which you can find in the Creature submenu.
To see auto-population from the database select the creature with the ID **40468**.
> feat(creature): creature-template-movement

- src/app/main/main-window/sidebar/sidebar.component.scss
Closes https://github.com/azerothcore/Keira3/issues/1695  
It seems that Font Awesome was upgraded from v5 to v6. Version 6 introduced breaking changes on how to use the icons with pseudo-elements. You can find the changes under [this link](https://fontawesome.com/docs/web/setup/upgrade/pseudo-elements), especially the paragraph "Updating Font Rule Syntax". Normally there should be an automated backward compatibility feature, but it seems this didn't work here.
The result after the changes is the following:
> fix: adapt sidebar icon styling to fontawesome 6

- src/app/shared/modules/sai-editor/sai-comment-generator.service.spec.ts
- src/app/shared/modules/sai-editor/sai-comment-generator.service.ts
closes https://github.com/azerothcore/Keira3/issues/2080
given a creature SAI with the following phase, the generated comment is wrong
current generated comment: `Phases 1 & 2 & 8 & 256`
expected comment: `phases 1 & 2 & 4 & 9`
> fix: SAI phase comment calculation, closes #2080

- src/app/shared/modules/sai-editor/constants/sai-actions.ts
Saw it in action and tested the event ingame. Setting both to 0 removes the effect and does not give an error.
> Change misleading description in sai-actions.ts

- .github/workflows/build-mac.yml
The macOS 10.15 Actions runner image [started our deprecation process](https://github.com/actions/virtual-environments/issues/5583) on 5/31/22 and will be fully unsupported by 8/30/22. To raise awareness of the upcoming removal, jobs using macOS 10.15 will temporarily fail during scheduled time periods defined below:
- July 21, 12:00 UTC – July 22, 18:00 UTC
- July 27, 00:00 UTC – July 28, 00:00 UTC
- August 3, 00:00 UTC – August 4, 00:00 UTC
- August 15, 00:00 UTC – August 16, 00:00 UTC
- August 26, 00:00 UTC – August 27, 00:00 UTC
Workflows using the macos-10.15 YAML workflow label should be updated to macos-11, macos-12, or macos-latest. You can always get up-to-date information on our tools by reading about the [software](https://github.com/actions/virtual-environments) in GitHub …
> feat. update workflows macOS

- README.md
Hello everyone, long time no see,
As i don't have time to maintain the AUR package and a mac user from some time, the aur package got out of my hands, currently it got moved to https://aur.archlinux.org/account/muflone/ who instead of maintaining or keeping the AUR package active, removed it.
So, the removal of the AUR reference is needed as it is not valid anymore.
> Remove aur package

- apps/keira/src/app/routes.ts
- apps/keira/src/assets/i18n/de.json
- apps/keira/src/assets/i18n/el.json
- apps/keira/src/assets/i18n/en.json
- apps/keira/src/assets/i18n/es.json
- apps/keira/src/assets/i18n/fr.json
- apps/keira/src/assets/i18n/it.json
- apps/keira/src/assets/i18n/ko.json
- apps/keira/src/assets/i18n/nl.json
- apps/keira/src/assets/i18n/pl.json
- apps/keira/src/assets/i18n/pt.json
- apps/keira/src/assets/i18n/ro.json
- apps/keira/src/assets/i18n/ru.json
- apps/keira/src/assets/i18n/sk.json
- apps/keira/src/assets/i18n/sv.json
- apps/keira/src/assets/i18n/zh.json
- libs/features/creature/src/creature-handler.service.ts
- libs/features/creature/src/creature-text/creature-text.component.html
- libs/features/creature/src/creature-text/creature-text.component.ts
- libs/features/creature/src/creature-text/creature-text.integration.spec.ts
- libs/features/creature/src/creature-text/creature-text.service.spec.ts
- libs/features/creature/src/creature-text/creature-text.service.ts
- libs/features/creature/src/index.ts
- libs/main/main-window/src/sidebar/sidebar.component.html
- libs/shared/acore-world-model/src/entities/creature-text.type.ts
- libs/shared/acore-world-model/src/index.ts
- libs/shared/acore-world-model/src/options/text-range.ts
- libs/shared/acore-world-model/src/options/text-type.ts
Relates to:
#1819 
#1078 
Improvements:
link to broadcast_text
> feat(creature): new creature_text editor

- apps/keira/src/assets/i18n/de.json
- apps/keira/src/assets/i18n/el.json
- apps/keira/src/assets/i18n/en.json
- apps/keira/src/assets/i18n/es.json
- apps/keira/src/assets/i18n/fr.json
- apps/keira/src/assets/i18n/it.json
- apps/keira/src/assets/i18n/ko.json
- apps/keira/src/assets/i18n/nl.json
- apps/keira/src/assets/i18n/pl.json
- apps/keira/src/assets/i18n/pt.json
- apps/keira/src/assets/i18n/ro.json
- apps/keira/src/assets/i18n/ru.json
- apps/keira/src/assets/i18n/sk.json
- apps/keira/src/assets/i18n/sv.json
- apps/keira/src/assets/i18n/zh.json
- libs/features/creature/src/creature-equip-template/creature-equip-template.component.html
- libs/features/creature/src/creature-equip-template/creature-equip-template.component.ts
- libs/features/creature/src/creature-onkill-reputation/creature-onkill-reputation.component.html
- libs/features/creature/src/creature-template-resistance/creature-template-resistance.component.html
- libs/features/creature/src/creature-template-resistance/creature-template-resistance.component.ts
In: "difficulty_entry_3": "Entry of the equivalent creature in 25man Heroic Raid",
Corrected `difficulty_entry_3` to `DIFFICULTY_ENTRY_3` to match the others.
Created: 
`ITEMID1`: "This is the item number of the equipment used in the right hand from Item.dbc.",
`ITEMID2`: "This is the item number of the equipment used in the left hand from Item.dbc.",
`ITEMID3`: "This is the item number of the equipment used in the ranged slot from Item.dbc."
~Created:~
~TEMPLATE_RESISTANCE.SCHOOL: `1 - SPELL_SCHOOL_HOLY; 2 - SPELL_SCHOOL_FIRE; 3 - SPELL_SCHOOL_NATURE; 4 - SPELL_SCHOOL_FROST; 5 - SPELL_SCHOOL_SHADOW; 6 - SPELL_SCHOOL_ARCANE`~
Added `[tooltip]="'UNIQUE_ID' | translate: { ENTITY: 'creature' }` to creatureID to match the others Infos for the CreatureID
Created: …
> chore(Creature): improved several tooltips

- .github/workflows/sync_i18n.yml
- scripts/sync_i18n.py
Using en.json as default to sync all keys across the available json files. 
Commits the adjustments if necessary.
Closes #3211
Example fix can be seen here:
https://github.com/Exitare/Keira3/commit/435a29eca18f67351cfd4b7e8edaf47335aefffc
> ci: add new workflow to sync i18n files

- libs/features/creature/src/creature-template-model/creature-template-model.integration.spec.ts
- libs/shared/acore-world-model/src/entities/creature-template-model.type.ts
> chore(creature_template_model): change initial probability from 0 to 1

- apps/keira/src/app/scss/_utils.scss
- libs/features/creature/src/npc-vendor/npc-vendor.component.html
Closes #3248
Item extended cost now inherits style from parent component. 
Additionally, I removed a duplicate disabled element.
> fix(npc-vendor): wrong color for item extended cost.

- libs/features/item/src/item-template/item-template.component.html
- libs/shared/selectors/src/selectors/flags-selector/flags-selector-modal.component.spec.ts
- libs/shared/selectors/src/selectors/flags-selector/flags-selector-modal.component.ts
- libs/shared/selectors/src/selectors/flags-selector/flags-selector.model.ts
- libs/shared/selectors/src/selectors/flags-selector/flags.service.spec.ts
- libs/shared/selectors/src/selectors/flags-selector/flags.service.ts
Closes #3239
It's possible to override the default behavior for the flag selector now. If the behavior is overridden, it defaults to -1 when all bits are unset. Otherwise everything stays the same.
> Add default behaviour override for flag selectors.

- libs/features/sql-editor/src/sql-editor.component.html
Progresses: [3131](https://github.com/azerothcore/Keira3/issues/3131)
- disabled spellcheck
- moved the sql on right top side
> feat(sql-editor-minor-improvements)

- libs/shared/sai-editor/src/constants/sai-actions.ts
ACTION_38_SET_IN_COMBAT_WITH_ZONE does not any params for range, it uses the target and only target type 9 (creature_range)
From:
action info
action param1 info
To:
action info
Refer to this: https://discord.com/channels/217589275766685707/536630256048799744/1385621105070575616 in the AC discord
> fix(SAI): ACTION_38_SET_IN_COMBAT_WITH_ZONE tooltip + removed unused param

- libs/features/gameobject/src/select-gameobject/select-gameobject.component.html
GameObject type Select displays the correct enum name
culprit: 
- https://github.com/azerothcore/Keira3/blob/1c7537f14029474f6bdc1ee28c13f59dcc4ea124/libs/features/gameobject/src/select-gameobject/select-gameobject.component.ts#L40
1. gameobject tab, select
2. search for door
3. See that type name is off by 1
> fix(features/gameobject): display correct type name
